sonar.projectKey=infra-abogados-iac
sonar.projectName=INFRA-ABOGADOS-IAC
sonar.projectVersion=1.0

sonar.sources=frontend,lambda,terraform
sonar.tests=lambda/audiencias/tests
sonar.test.inclusions=**/tests/**/*.py

# Ignorar cosas que no interesan
sonar.exclusions=**/node_modules/**,**/.terraform/**,**/*.zip,**/ci/**
sonar.sourceEncoding=UTF-8
